package com.developer.test.service;

import com.developer.test.exception.ResourceNotFoundException;
import com.developer.test.exception.ValidationException;
import com.developer.test.model.Task;
import com.developer.test.model.User;
import com.developer.test.dto.StatsResponse;
import com.developer.test.repository.TaskRepository;
import com.developer.test.repository.UserRepository;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Set;

/**
 * Service layer for users and tasks.
 * Uses JPA repositories backed by H2 database for persistent storage.
 */
@Service
public class DataStore {

    private static final Set<String> VALID_STATUSES = Set.of("pending", "in-progress", "completed");

    private final UserRepository userRepository;
    private final TaskRepository taskRepository;

    public DataStore(UserRepository userRepository, TaskRepository taskRepository) {
        this.userRepository = userRepository;
        this.taskRepository = taskRepository;
    }

    @Cacheable("users")
    public List<User> getUsers() {
        return userRepository.findAll();
    }

    @Cacheable(value = "user", key = "#id")
    public User getUserById(int id) {
        return userRepository.findById(id).orElse(null);
    }

    @Cacheable(value = "tasks", key = "#status + '-' + #userId")
    public List<Task> getTasks(String status, String userId) {
        boolean hasStatus = status != null && !status.isEmpty();
        boolean hasUserId = userId != null && !userId.isEmpty();

        if (hasStatus && hasUserId) {
            return taskRepository.findByStatusAndUserId(status, Integer.parseInt(userId));
        } else if (hasStatus) {
            return taskRepository.findByStatus(status);
        } else if (hasUserId) {
            return taskRepository.findByUserId(Integer.parseInt(userId));
        } else {
            return taskRepository.findAll();
        }
    }

    @Cacheable("stats")
    public StatsResponse getStats() {
        List<Task> allTasks = taskRepository.findAll();

        StatsResponse stats = new StatsResponse();
        stats.getUsers().setTotal((int) userRepository.count());
        stats.getTasks().setTotal(allTasks.size());

        for (Task task : allTasks) {
            switch (task.getStatus()) {
                case "pending":
                    stats.getTasks().setPending(stats.getTasks().getPending() + 1);
                    break;
                case "in-progress":
                    stats.getTasks().setInProgress(stats.getTasks().getInProgress() + 1);
                    break;
                case "completed":
                    stats.getTasks().setCompleted(stats.getTasks().getCompleted() + 1);
                    break;
            }
        }

        return stats;
    }

    /**
     * Creates a new user. ID is auto-generated by the database.
     */
    @CacheEvict(value = {"users", "user", "stats"}, allEntries = true)
    public User createUser(String name, String email, String role) {
        if (userRepository.existsByEmailIgnoreCase(email)) {
            throw new ValidationException("Email '" + email + "' already exists");
        }
        User user = new User(name, email, role);
        return userRepository.save(user);
    }

    /**
     * Creates a new task. Validates status and userId.
     */
    @CacheEvict(value = {"tasks", "stats"}, allEntries = true)
    public Task createTask(String title, String status, int userId) {
        validateStatus(status);
        if (!userRepository.existsById(userId)) {
            throw new ValidationException("User with ID " + userId + " does not exist");
        }
        Task task = new Task(title, status, userId);
        return taskRepository.save(task);
    }

    /**
     * Updates an existing task. Only non-null fields are updated (partial update).
     */
    @CacheEvict(value = {"tasks", "stats"}, allEntries = true)
    public Task updateTask(int id, String title, String status, Integer userId) {
        Task task = taskRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Task with ID " + id + " not found"));

        if (status != null) {
            validateStatus(status);
            task.setStatus(status);
        }
        if (userId != null) {
            if (!userRepository.existsById(userId)) {
                throw new ValidationException("User with ID " + userId + " does not exist");
            }
            task.setUserId(userId);
        }
        if (title != null) {
            task.setTitle(title);
        }
        return taskRepository.save(task);
    }

    public boolean userExists(int id) {
        return userRepository.existsById(id);
    }

    private void validateStatus(String status) {
        if (!VALID_STATUSES.contains(status)) {
            throw new ValidationException("Invalid status: '" + status + "'. Must be one of: " + VALID_STATUSES);
        }
    }
}
